# Generated by Django 5.1 on 2024-10-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('date_creat', models.DateField()),
                ('sap_vendor_no', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('so_chung_nhan', models.CharField(max_length=255)),
                ('ngay_het_hieu_luc', models.DateField()),
                ('tinh_trang', models.CharField(max_length=255)),
                ('tinh_trang_bao_cao', models.CharField(max_length=255)),
                ('ma_ho_so', models.CharField(max_length=255)),
            ],
        ),
    ]
