# Generated by Django 5.1 on 2024-10-03 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_creat',
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ma_ho_so',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sap_vendor_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='so_chung_nhan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tinh_trang',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tinh_trang_bao_cao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(max_length=200),
        ),
    ]
