# Generated by Django 5.1 on 2024-10-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_date_creat_product_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ma_ho_so',
            new_name='certification_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ngay_het_hieu_luc',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='so_chung_nhan',
            new_name='file_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tinh_trang',
            new_name='report_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tinh_trang_bao_cao',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sap_vendor_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(max_length=255),
        ),
    ]
