# Generated by Django 5.1 on 2024-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('SAP_Vendor_No', models.CharField(max_length=50)),
                ('Vendor', models.CharField(max_length=200)),
                ('so_chung_nhan', models.CharField(max_length=50)),
                ('ngay_het_hieu_luc', models.DateField()),
                ('tinh_trang', models.CharField(max_length=50)),
                ('tinh_trang_bao_cao', models.CharField(max_length=50)),
                ('ma_ho_so', models.CharField(max_length=50)),
            ],
        ),
    ]
