# Generated by Django 5.1 on 2024-10-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_ngay_het_hieu_luc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.CharField(max_length=50),
        ),
    ]
