# Generated by Django 5.1 on 2024-11-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_product_sap_vendor_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Vendor_name',
            field=models.CharField(default='Default Vendor Name', max_length=200),
        ),
    ]
